### ISSUE TITLE
General HASS error: can't find make

### ISSUE THREAD

**Issue by sboger** [gl-inet/home-assistant-on-openwrt#4]
This is so specific, I'm unsure where to submit it. HASS is erroring out installing several python packages due to make not being found. Especially, the zwave modules, but below shows the PyNaCl module.

How do I get make properly installed on the GL-S1300? Or do I need to build these on a different system and bring them into the GL-S1300? I'm trying to get a full HASS system up with a HUSBZB-1.

```

2020-09-08 01:11:53 INFO (SyncWorker_7) [homeassistant.util.package] Attempting install of PyNaCl==1.3.0




2020-09-08 01:14:53 ERROR (SyncWorker_7) [homeassistant.util.package] Unable to install package PyNaCl==1.3.0: ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpmk6tdbjg
       cwd: /tmp/pip-install-8gty0l77/pynacl
  Complete output (72 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.6
  creating build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/utils.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/signing.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/secret.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/public.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/hashlib.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/hash.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/exceptions.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/encoding.py -> build/lib.linux-armv7l-3.6/nacl
  copying src/nacl/__init__.py -> build/lib.linux-armv7l-3.6/nacl
  creating build/lib.linux-armv7l-3.6/nacl/pwhash
  copying src/nacl/pwhash/scrypt.py -> build/lib.linux-armv7l-3.6/nacl/pwhash
  copying src/nacl/pwhash/argon2id.py -> build/lib.linux-armv7l-3.6/nacl/pwhash
  copying src/nacl/pwhash/argon2i.py -> build/lib.linux-armv7l-3.6/nacl/pwhash
  copying src/nacl/pwhash/_argon2.py -> build/lib.linux-armv7l-3.6/nacl/pwhash
  copying src/nacl/pwhash/__init__.py -> build/lib.linux-armv7l-3.6/nacl/pwhash
  creating build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/utils.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/sodium_core.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/randombytes.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_sign.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_shorthash.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_secretstream.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_secretbox.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_scalarmult.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_pwhash.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_kx.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_hash.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_generichash.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_box.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/crypto_aead.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  copying src/nacl/bindings/__init__.py -> build/lib.linux-armv7l-3.6/nacl/bindings
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_clib
  Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-9y_s05j3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 217, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-9y_s05j3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-9y_s05j3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-9y_s05j3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 255, in <module>
      "Programming Language :: Python :: 3.7",
    File "/tmp/pip-build-env-9y_s05j3/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/core.py", line 148, in setup
    File "/dist.py", line 955, in run_commands
    File "/dist.py", line 974, in run_command
    File "/tmp/pip-build-env-9y_s05j3/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/cmd.py", line 313, in run_command
    File "/dist.py", line 974, in run_command
    File "/build.py", line 135, in run
    File "/cmd.py", line 313, in run_command
    File "/dist.py", line 974, in run_command
    File "setup.py", line 159, in run
      raise Exception("ERROR: The 'make' utility is missing from PATH")
  Exception: ERROR: The 'make' utility is missing from PATH
  ----------------------------------------
  ERROR: Failed building wheel for PyNaCl
ERROR: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
```

**Comment by YaoSir** [comment]
It's caused by a wrong version of PyNaCl. I have  modified the version of PyNaCl to 1.3.0 .Try again.
