### ISSUE TITLE
Install python module: PyNaCl

### ISSUE THREAD

**Issue by ghost** [gl-inet/home-assistant-on-openwrt#5]
Home Assistant
on my Mybooklive with version Powered by LuCI openwrt-19.07 branch (git-20.341.57626-51f55b5) / OpenWrt 19.07.5 r11257-5090152ae3

I've tried everything to urge this pyton module, always give me this error:

Install python module: PyNaCl...... try 1.
Collecting pynacl==1.3.0
Downloading PyNaCl-1.3.0.tar.gz (3.4 MB)
|████████████████████████████████| 3.4 MB 2.0 MB/s
Installing build dependencies ... error
WARNING: Discarding https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz#sha256=0c6100edd16fefd1557da078c7a31e7b7d7a52ce39fdca2bec29d4f7b6e7600c (from https://pypi.org/simple/pynacl/). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9ajd5wnn/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cffi>=1.4.1; python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pynacl==1.3.0
ERROR: No matching distribution found for pynacl==1.3.0

**Comment by darthdub1979** [comment]
File "get-pip.py", line 24184, in <module>
    main()
  File "get-pip.py", line 133, in main
    fp.write(b85decode(DATA.replace(b"\n", b"")))
  File "/usr/lib/python3.7/base64.py", line 472, in b85decode
MemoryError
 Download and install pip...... try 5.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1882k  100 1882k    0     0  2241k      0 --:--:-- --:--:-- --:--:-- 2312k
Traceback (most recent call last):
  File "get-pip.py", line 24184, in <module>
    main()
  File "get-pip.py", line 133, in main
    fp.write(b85decode(DATA.replace(b"\n", b"")))
  File "/usr/lib/python3.7/base64.py", line 472, in b85decode
MemoryError
 ERROR! Install pip failed,  exit.
root@TusTco:~/home-assistant-on-openwrt# hass -c /data/.homeassistant
-ash: hass: not found
root@TusTco:~/home-assistant-on-openwrt# opkg install hass

**Comment by darthdub1979** [comment]
it may be the base64.py ??? trying to rub on my EA3500 linksys

**Comment by ajinkyabawaskar** [comment]
Are there any updates on this? I am facing the same issue, installing home-assistant manually on OpenWrt virtual machine (x86_64)

**Comment by darthdub1979** [comment]
I ran out of ram I thought it was gonna work everything is working good but
during the compile process I just didn’t have enough ram

**Comment by ajinkyabawaskar** [comment]
Yes, I suspected it had something to do with the compiling process. For future readers that end up here, the solution is to "[Cross-compile](https://openwrt.org/docs/guide-developer/crosscompile)" the program on your computer and then copy the `.ipk` file to device running OpenWrt & install using `opkg`

**Comment by darthdub1979** [comment]
how do i do that
